import { useState } from 'react';
import { Button } from './ui/button';
import { Download, Loader2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

interface TranscriptDownloadProps {
  videoId: string;
  videoTitle: string;
}

export const TranscriptDownload = ({ videoId, videoTitle }: TranscriptDownloadProps) => {
  const [loading, setLoading] = useState(false);
  const { toast } = useToast();

  const downloadTranscript = async () => {
    setLoading(true);
    try {
      // Fetch the full transcription
      const { data: transcription, error: transcriptionError } = await supabase
        .from('transcriptions')
        .select('full_text')
        .eq('video_id', videoId)
        .single();

      if (transcriptionError) throw transcriptionError;

      if (!transcription) {
        toast({
          title: "No transcript found",
          description: "This video doesn't have a transcript yet.",
          variant: "destructive"
        });
        return;
      }

      // Fetch video details
      const { data: video, error: videoError } = await supabase
        .from('videos')
        .select(`
          title,
          published_at,
          url,
          youtube_channels (channel_name)
        `)
        .eq('id', videoId)
        .single();

      if (videoError) throw videoError;

      // Format the transcript document
      const channelName = (video.youtube_channels as any)?.channel_name || 'Unknown';
      const publishedDate = new Date(video.published_at).toLocaleDateString();
      
      const document = `
Legislative Session Transcript
==============================

Title: ${video.title}
Channel: ${channelName}
Date: ${publishedDate}
URL: ${video.url}

Transcript:
-----------

${transcription.full_text}

---
Generated by Legislative Content Analysis System
Downloaded: ${new Date().toLocaleString()}
`;

      // Create a blob and download
      const blob = new Blob([document], { type: 'text/plain' });
      const url = window.URL.createObjectURL(blob);
      const link = window.document.createElement('a');
      link.href = url;
      link.download = `transcript-${videoTitle.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.txt`;
      window.document.body.appendChild(link);
      link.click();
      window.URL.revokeObjectURL(url);
      window.document.body.removeChild(link);

      toast({
        title: "Success",
        description: "Transcript downloaded successfully"
      });
    } catch (error) {
      console.error('Error downloading transcript:', error);
      toast({
        title: "Error",
        description: "Failed to download transcript",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={downloadTranscript}
      disabled={loading}
    >
      {loading ? (
        <>
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Downloading...
        </>
      ) : (
        <>
          <Download className="mr-2 h-4 w-4" />
          Download Transcript
        </>
      )}
    </Button>
  );
};
